---

- hosts: localhost
  tasks:
    - name: Remediate Cluster - Run vRO Workflow
      run_vro_wf:
        vro_server: "https://vro.lab.local:8281"
        username: "Administrator@vsphere.local"
        password: "XXX"
        workflow_id: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
        input_values:
          vCenter: https://services-vcsa.vro.lab.local:443/sdk
          clusterName: LAB01
          hosts:
            - 10.10.0.1
            - 10.10.0.2
